sudo: required
services:
  - docker

before_install:
  - docker build -t lioartoil/docker-react-2 -f Dockerfile.dev .

script:
  - docker run lioartoil/docker-react-2 npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-306476627547'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
